---
title: "ENVS 193DS Final"
author: "Emilio Ojemann"
date: 2026-06-09
format: 
  pdf:
    toc: true
execute:
  message: false
  warning: false
---

# [GitHub repository](https://github.com/beojemann/ENVS-193DS_spring-2026_final)

# Set Up

Created repository, added description and README

```{r}
#| label: setup

# read in packages
library(tidyverse)
library(here)
library(janitor)

# read in nest observation data

# read in personal dinner cooking data
```

# Problem 1. Research writing

## a. Transparent statistical methods

In part 1, they used a binomial generalized linear model (aka logistic). The response is a binary outcome: the probability of American Avocet microhabitat use (it either is used or it is not). The predictor is distance to water edge, so it is continuous. This makes sense to use a binomial GLM to test whether a continuous predictor variable relates to a binary response.

<br>

In part 2, the used a chi-square test. Both the response (habitat type, 5 levels) and the predictor (bird species, 3 levels) variables are categorical. It makes sense to use chi-square because they seeing if a relationship exists between categories. 

## b. Suggestions for rewriting

Part 1: The probability that American Avocet's use microhabitat depends on how far the microhabitat is from the water's edge

<br>

Part 2: There is a difference in the habitats that the three bird species (American Avocet, Forster's Tern, and Black-necked Stilt) use, so there are some species that are found in certain habitats more than others.

## c. Further analysis

An additional variable that might influence the probability of American Avocet microhabitat use is the **water depth**. This is a continuous variable, measured in centimeters with a marked pole. As with most wading birds, American Avocets primarily feed by sweeping their bills through the water. It is thus likely that a microhabitat with shallower water will be used more than one with deep water, as it is easier to feed in.

# Problem 2. Data analysis

## a. Clean and wrangle

## b. Response variable

## c. Purpose of study

## d. Table of models

## e. Running the models

## f. Selecting the best model

## g. Checking the diagnostics

## h. Visualizing model predictions

## i. Writing figure caption

## j. Calculating model predictions

## k. Interpreting results

# Problem 3. Affective and exploratory visualizations

## a. Comparing visualizations

## b. Designing an analysis

## c. Checking assumptions and running analysis

## d. Creating a visualization

## e. Writing a caption

## f. Writing about results

## g. Sharing affective visualization
